<?php
declare(strict_types=1);

// @codeCoverageIgnoreStart

return [
    'roles'       => [
        'admin'          => [],
        'main_manager'   => ['admin'],
        'manager'        => ['main_manager'],
        'office_admin'   => ['manager'],
        'office_manager' => ['office_admin'],
        'user'           => ['office_manager'],
        'referral'       => ['user'],
        'guest'          => ['user'],
    ],
    'permissions' => [
        'admin'        => [
            'admin.left-menu',
            'admin.index',
            'admin.rfn',
            'admin.roles',
            'admin.role',
            'admin.settings',
            'admin.ofd.edit',
            'admin.service',
            'admin.service.edit',
            'admin.tariff',
            'admin.tariff.edit',
            'admin.referral',
            'admin.apiKey',
            'admin.processing.edit',
            'admin.processing.rm',
            'admin.kkt',
            'admin.kkt.edit',
            'admin.kkt.closeShift',
            'admin.kkt.info',
            'admin.kkt.closeFn',
            'admin.file',
            'admin.file.edit',
        ],
        'main_manager' => [
            'main_manager.left-menu',
            'admin.kkt',
            'admin.kkt.edit',
            'admin.kkt.closeShift',
            'admin.kkt.info',
            'admin.kkt.closeFn',
        ],
        'manager'      => [
            'manager.left-menu',
            'admin.company.list',
            'admin.company.edit',
            'admin.company.delete',
            'admin.moneyHistory',
            'admin.moneyHistory.edit',
            'admin.user',
            'admin.users',
            'admin.ofd',
            'admin.invoice',
            'admin.invoice.edit',
            'admin.invoice.download',
            'admin.kkt.deleted',
            'admin.referral',
            'admin.processing',
            'admin.processing.view',
        ],
        'office_admin' => [
            'office.company',
            'office.company.edit',
            'office.company.stepOne',
            'office.company.stepTwo',
            'office.company.stepThree',
            'office.company.stepFour',
            'office.oferta',
            'office.billing',
            'office.invoice',
            'office.kkt.get',
            'office.kkt.rnm',
            'office.kkt.info',
            'office.access',
            'office.check',
            'office.check.view',
            'office.kkt.list',
            'office.kkt.files',
            'office.kkt.kkt-tariff',
            'office.kkt.statement',
            'office.kkt.registration',
        ],
        'referral'     => [
            'office.referral',
            'office.referralpay',
        ],
        'user'         => [
            'logout',
            'home',
            'user.changePassword',
            'user.rollback',
            'user.profile',
            'insales.settings.edit',
            'insales.settings.view',
        ],
        'guest'        => [
            'landing',
            'api.landing',
            'retarget',

            'login',
            'register',
            'user.confirm',
            'user.forget',
            'user.restore',

            //api
            'api.v1.token',
            'api.v1.registerOperation',
            'api.v1.getProcessing',
            'api.v1.getProcessingExternal',

            //api Atol
            'apiatol.v1.token',
            'apiatol.v1.registerOperation',
            'apiatol.v1.getProcessing',

            //api Insales
            'insales.login',
            'insales.autologin',
            'insales.printcheck',
            'insales.uninstall',
            'insales.install',
            'insales.manual',
        ],
    ],
    'asserts'     => [
        'login'    => \Permission\Asserts\NotLogin::class,
        'register' => \Permission\Asserts\NotLogin::class,
    ],
];
// @codeCoverageIgnoreEnd
