<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 18.09.18
 * Time: 9:21
 */
/** @var \App\Renderer\PhpRenderer $this */
/** @var \Auth\Entity\User $user */
/** @var \Office\Entity\ReferralPayment[] $payments */
?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Мои начисления с рефералов</h2>
                <div class="clearfix"></div>
                Ссылка для привлечения https://online.schetmash.com/lk/user/register?referral=<?php echo $user->getId(); ?>
            </div>
            <div class="x_content">
                    <form action="" method="get" class="form-inline">
                        <h5>Фильтр</h5>
                        <div class="form-group">
                            <input type="text" class="form-control" name="filter[name]" value="<?php echo $filter['name']; ?>"
                             placeholder="Фамилия или компания">
                        </div>
                        <div class="form-group">
                            <select name="filter[pay]" class="form-control">
                                <option></option>
                                <option <?php if($filter['pay'] == 0) { echo 'selected'; } ?> value="0">Ожидает выплаты</option>
                                <option <?php if($filter['pay'] == 1) { echo 'selected'; } ?> value="1">Выплачено</option>
                            </select>
                        </div>
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary form-control">Найти</button>
                        </div>
                    </form>
                    <br>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>
                            <a href="<?php $field = 'r.id';
                                echo $this->url('office.referralpay', [], ['sort' => $field,'order' => $order]); ?>"> #
                                <?php if ($sortType === $field) { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </a>
                        </th>
                        <th>
                            <a href="<?php $field = 'u.lastName';
                                echo $this->url('office.referralpay', [], ['sort' => $field,'order' => $order]); ?>"> ФИО реферала
                                <?php if ($sortType === $field) { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </a>
                        </th>
                        <th>
                            <a href="<?php $field = 'c.title';
                                 echo $this->url('office.referralpay', [], ['sort' => $field,'order' => $order]); ?>"> Компания
                                <?php if ($sortType === $field) { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </a>
                        </th>
                        <th>
                            <a href="<?php $field = 'r.datetime';
                                 echo $this->url('office.referralpay', [], ['sort' => $field,'order' => $order]); ?>"> Дата начисления
                                <?php if ($sortType === $field) { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </a>
                        </th>
                        <th>
                            <a href="<?php $field = 'r.sum';
                                 echo $this->url('office.referralpay', [], ['sort' => $field,'order' => $order]); ?>"> Сумма
                                <?php if ($sortType === $field) { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </a>
                        </th>
                        <th>
                            <a href="<?php $field = 'r.pay';
                                 echo $this->url('office.referralpay', [], ['sort' => $field,'order' => $order]); ?>">Статус
                                <?php if ($sortType === $field) { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </a>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($referrals as $item) {
                        ?>
                        <tr>
                            <td><?php echo $item->getId(); ?></td>
                            <td><?php echo $this->escapeHtml($item->getFromUser()->getFio()); ?></td>
                            <td><?php echo $this->escapeHtml($item->getCompany()->getTitle()); ?></td>
                            <td><?php echo $item->getDatetime()->format('d.m.Y'); ?></td>
                            <td><?php echo $item->getSum(); ?></td>
                            <td><?php echo ( ($item->getPay() === 1) ? '<span class="label label-success">Выплачено</span>' : '<span class="label label-warning">Ожидает выплаты</span>' ); ?></td>
                        </tr>
                        <?php
                    }
                    ?>
                    </tbody>
                </table>
                <?php echo $this->paginator($paginator, 'office::paginator'); ?>
            </div>
        </div>
    </div>
</div>