<?php
/** @var \App\Renderer\PhpRenderer $this */
/** @var array $data */
?>
<div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel tile">
        <div class="x_title">
            <h2><?php echo $data['label']; ?></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <?php /*
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                      </ul>
                    </li>
                    */ ?>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <h4>Всего: <?php echo $data['total']; ?> шт</h4>

            <?php foreach ($data['items'] as $item) {
                $percent = round(100 * $item['value'] / $data['total'], 1);
                ?>
                <div class="widget_summary">

                    <div class="w_left w_25">
                        <span><?php echo $item['label']; ?></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-green" role="progressbar" aria-valuenow="<?php echo $percent; ?>" aria-valuemin="<?php echo $percent; ?>"
                                 aria-valuemax="100" style="width: <?php echo $percent; ?>%;">
                                <span class="sr-only"><?php echo $percent; ?>%</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_left w_20">
                        <span> <?php echo $percent.'% / '.$item['value'].'шт'; ?></span>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php } ?>


        </div>
    </div>
</div>