<?php
/** @var \App\Renderer\PhpRenderer $this */
/** @var array $data */
?>
<div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel tile ">
        <div class="x_title">
            <h2><?php echo $data['label']; ?></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <?php /*
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                      </ul>
                    </li>
                    */ ?>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <?php foreach ($data['th'] as $item) { ?>
                        <th><?php echo $this->escapeHtml($item); ?></th>
                    <?php } ?>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($data['items'] as $items) { ?>
                    <tr>
                        <?php foreach ($items as $td) { ?>
                            <td> <?php echo $this->escapeHtml($td); ?></td>
                        <?php } ?>
                    </tr>
                <?php } ?>
                </tbody>
            </table>


        </div>
    </div>
</div>
<?php /*$this->inlineScript()->prependFile('/assets/build/js/jquery.dataTables.min.js');*/ ?>
<script>
    /* jquery('#datatable').DataTable();*/
</script>