<?php
/** @var \App\Renderer\PhpRenderer $this */
/** @var array $data */
?>
<div class="col-md-8 col-sm-8 col-xs-12">
    <div class="x_panel tile ">
        <div class="x_title">
            <h2><?php echo $data['label']; ?></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <?php foreach ($data['items'] as $company) { ?>
                <h3>Компания: <?php echo $company['title']; ?></h3>
                <?php foreach ($company['shops'] as $shop) {
                    if (\count($shop['kkts'])) {
                        ?>
                        <h4>Магазин: <?php echo $this->escapeHtml($shop['title']); ?></h4>
                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <?php foreach ($shop['th'] as $item) { ?>
                                    <th><?php echo $this->escapeHtml($item); ?></th>
                                <?php } ?>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($shop['kkts'] as $kkt) { ?>
                                <tr>
                                    <?php foreach ($kkt as $td) { ?>
                                        <td> <?php echo $this->escapeHtml($td); ?></td>
                                    <?php } ?>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    <?php }
                } ?>
            <?php } ?>
        </div>
    </div>
</div>