<?php $this->headTitle('400 Bad Request'); ?>

<section class="error-block">
    <div class="error-block__inner inner">
        <h1 class="error-block__not-found">Неверные данные!
        </h1>
        <p class="error-block__number">400
        </p>
        <p class="error-block__text">Url для данного запроса составлен неверно!
        </p>
        <p class="error-block__text">Перейдите на<a href="<?php echo $this->url('home');?>"> главную страницу</a>.
        </p>
    </div>
</section>