<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 18.03.18
 * Time: 16:22
 */
/** @var \App\Renderer\PhpRenderer $this */
/** @var \Auth\Entity\User $user */
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Мои компании</h2>
                    <a href="<?php echo $this->url('office.company.stepOne', ['id' => 0]); ?>" class="btn btn-primary pull-right">Добавить</a>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Название</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        /** @var \Office\Entity\Company $company */
                        foreach ($user->getCompany()->filter(
                            function ($company) {
                                return !$company->getIsDeleted();
                            }
                        ) as $company) {
                            ?>
                            <tr>
                                <th scope="row"><?php echo $company->getId(); ?></th>
                                <td>
                                    <a href="<?php echo $this->url('office.company.stepOne', ['id' => $company->getId()]); ?>">
                                        <?php echo $this->escapeHtml($company->getDefaultTitle()); ?>
                                    </a>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
