<?php

namespace DoctrineEntityProxy\__CG__\Office\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \Office\Entity\Company implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'title', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'inn', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'kpp', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'rawData', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ogrnIp', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ogrn', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'type', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'orgType', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'nalogSystem', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ipLastName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ipFirstName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ipMiddleName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'address', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'companyPhone', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'companyEmail', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'directorLastName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'directorFirstName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'directorMiddleName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'companyCheckEmail', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'isEnabled', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'isDeleted', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'balance', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'date', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ofd', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'user', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'shop', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'referral'];
        }

        return ['__isInitialized__', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'title', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'inn', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'kpp', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'rawData', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ogrnIp', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ogrn', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'type', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'orgType', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'nalogSystem', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ipLastName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ipFirstName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ipMiddleName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'address', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'companyPhone', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'companyEmail', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'directorLastName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'directorFirstName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'directorMiddleName', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'companyCheckEmail', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'isEnabled', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'isDeleted', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'balance', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'date', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'ofd', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'user', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'shop', '' . "\0" . 'Office\\Entity\\Company' . "\0" . 'referral'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Company $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setInn($inn = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInn', [$inn]);

        return parent::setInn($inn);
    }

    /**
     * {@inheritDoc}
     */
    public function getInn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInn', []);

        return parent::getInn();
    }

    /**
     * {@inheritDoc}
     */
    public function setKpp($kpp = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKpp', [$kpp]);

        return parent::setKpp($kpp);
    }

    /**
     * {@inheritDoc}
     */
    public function getKpp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKpp', []);

        return parent::getKpp();
    }

    /**
     * {@inheritDoc}
     */
    public function setRawData($rawData = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRawData', [$rawData]);

        return parent::setRawData($rawData);
    }

    /**
     * {@inheritDoc}
     */
    public function getRawData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRawData', []);

        return parent::getRawData();
    }

    /**
     * {@inheritDoc}
     */
    public function setOgrnIp($ogrnIp = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOgrnIp', [$ogrnIp]);

        return parent::setOgrnIp($ogrnIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getOgrnIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOgrnIp', []);

        return parent::getOgrnIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setOgrn($ogrn = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOgrn', [$ogrn]);

        return parent::setOgrn($ogrn);
    }

    /**
     * {@inheritDoc}
     */
    public function getOgrn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOgrn', []);

        return parent::getOgrn();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgType($orgType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgType', [$orgType]);

        return parent::setOrgType($orgType);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgType', []);

        return parent::getOrgType();
    }

    /**
     * {@inheritDoc}
     */
    public function setNalogSystem($nalogSystem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNalogSystem', [$nalogSystem]);

        return parent::setNalogSystem($nalogSystem);
    }

    /**
     * {@inheritDoc}
     */
    public function getNalogSystem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNalogSystem', []);

        return parent::getNalogSystem();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpLastName($ipLastName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpLastName', [$ipLastName]);

        return parent::setIpLastName($ipLastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpLastName', []);

        return parent::getIpLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpFirstName($ipFirstName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpFirstName', [$ipFirstName]);

        return parent::setIpFirstName($ipFirstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpFirstName', []);

        return parent::getIpFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpMiddleName($ipMiddleName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpMiddleName', [$ipMiddleName]);

        return parent::setIpMiddleName($ipMiddleName);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpMiddleName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpMiddleName', []);

        return parent::getIpMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyPhone($companyPhone = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyPhone', [$companyPhone]);

        return parent::setCompanyPhone($companyPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyPhone', []);

        return parent::getCompanyPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyEmail($companyEmail = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyEmail', [$companyEmail]);

        return parent::setCompanyEmail($companyEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyEmail', []);

        return parent::getCompanyEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirectorLastName($directorLastName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirectorLastName', [$directorLastName]);

        return parent::setDirectorLastName($directorLastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirectorLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirectorLastName', []);

        return parent::getDirectorLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirectorFirstName($directorFirstName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirectorFirstName', [$directorFirstName]);

        return parent::setDirectorFirstName($directorFirstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirectorFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirectorFirstName', []);

        return parent::getDirectorFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirectorMiddleName($directorMiddleName = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirectorMiddleName', [$directorMiddleName]);

        return parent::setDirectorMiddleName($directorMiddleName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirectorMiddleName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirectorMiddleName', []);

        return parent::getDirectorMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCheckEmail($companyCheckEmail = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCheckEmail', [$companyCheckEmail]);

        return parent::setCompanyCheckEmail($companyCheckEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCheckEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCheckEmail', []);

        return parent::getCompanyCheckEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEnabled($isEnabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEnabled', [$isEnabled]);

        return parent::setIsEnabled($isEnabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEnabled', []);

        return parent::getIsEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted($isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$isDeleted]);

        return parent::setIsDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalance($balance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalance', [$balance]);

        return parent::setBalance($balance);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalance', []);

        return parent::getBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfd(\Office\Entity\Ofd $ofd = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfd', [$ofd]);

        return parent::setOfd($ofd);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfd', []);

        return parent::getOfd();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\Auth\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\Auth\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function addShop(\Office\Entity\Shop $shop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShop', [$shop]);

        return parent::addShop($shop);
    }

    /**
     * {@inheritDoc}
     */
    public function removeShop(\Office\Entity\Shop $shop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShop', [$shop]);

        return parent::removeShop($shop);
    }

    /**
     * {@inheritDoc}
     */
    public function getShop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShop', []);

        return parent::getShop();
    }

    /**
     * {@inheritDoc}
     */
    public function addBalance(int $sum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBalance', [$sum]);

        return parent::addBalance($sum);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultTitle', []);

        return parent::getDefaultTitle();
    }

}
