<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 24.01.18
 * Time: 9:44
 */
/** @var \App\Renderer\PhpRenderer $this */
?>
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <!--                        <img src="/assets/cms/images/img.jpg" alt="">-->
                        <?php echo $this->escapeHtml($this->user->getUsername()); ?>
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="<?php echo $this->url('user.profile'); ?>"> Профиль</a></li>
                        <li><a href="<?php echo $this->url('user.changePassword'); ?>"> Смена пароля</a></li>
                        <!--                        <li>-->
                        <!--                            <a href="javascript:;">-->
                        <!--                                <span class="badge bg-red pull-right">50%</span>-->
                        <!--                                <span>Settings</span>-->
                        <!--                            </a>-->
                        <!--                        </li>-->
                        <!--                        <li><a href="javascript:;">Help</a></li>-->
                        <li>
                            <a href="<?php echo $this->url('logout'); ?>">
                                <i class="fa fa-sign-out pull-right"></i> Выход
                            </a>
                        </li>
                    </ul>
                </li>
                <?php
                if (!empty($_SESSION['rollback'])) {
                    ?>
                    <li class="">
                        <a title="Вернуться в админку" href="<?php echo $this->url('user.rollback'); ?>">Вернуться</a>
                    </li>
                    <?php
                }
                ?>
                <li class="">
                    <a href="tel:+74712734990" title="Позвонить менеджеру">
                        +7 (4712) 73-49-90
                    </a>
                </li>
                <li class="">
                    <a href="/upload/docs/instruction.pdf" target="_blank" title="Инструкция пользователя ЛК" id="instruction" style="text-decoration: underline;font-weight: bold;color: #000!important;">
                        Инструкция пользователя ЛК
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
