<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 23.11.18
 * Time: 9:12
 */
/** @var \App\Renderer\PhpRenderer $this */
/** @var \Office\Entity\MoneyHistory $item */
/** @var \Office\Entity\Company[] $companies */

$this->inlineScript()->prependFile('/assets/cms/vendors/validator/validator.js');
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">

                    <form class="form-horizontal form-label-left" novalidate method="post" action="?">
                        <span class="section">Добавление записи</span>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="company">
                                Компания <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="company" id="company" class="form-control col-md-7 col-xs-12">
                                    <?php
                                    foreach ($companies as $company) {
                                        ?>
                                        <option value="<?php echo $company->getId(); ?>">
                                            <?php echo $this->escapeHtml($company->getDefaultTitle()); ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                Тип <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="type" id="type" class="form-control col-md-7 col-xs-12" required>
                                    <?php
                                    foreach (\Office\Entity\MoneyHistory::TYPES as $key => $status) {
                                        ?>
                                        <option value="<?php echo $key; ?>"><?php echo $status; ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>


                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="sum">
                                Сумма <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="sum" class="form-control col-md-7 col-xs-12" name="sum"
                                       required="required" type="number">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">
                                Описание <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="title" class="form-control col-md-7 col-xs-12" name="title"
                                       required
                                       type="text">
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <button id="send" type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
