<?php
/** @var \App\Renderer\PhpRenderer $this */
/** @var \Office\Entity\MoneyHistory[] $history */
?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Списания</h2>
                <a class="btn btn-primary pull-right" href="<?php echo $this->url('admin.moneyHistory.edit', ['id' => 0]); ?>">Добавить</a>
                <div class="clearfix"></div>
            </div>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Дата</th>
                    <th>Сумма</th>
                    <th>Тип</th>
                    <th>Компания</th>
                    <th>Описание</th>
                    <th>Пользователь</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($history as $item) {
                    ?>
                    <tr>
                        <th scope="row">
                            <?php echo $item->getId(); ?>
                        </th>
                        <td>
                            <?php echo $item->getDatetime()->format('d.m.Y H:i:s'); ?>
                        </td>
                        <td>
                            <?php echo $item->getSum(); ?>
                        </td>
                        <td><?php echo $item->getType() ? 'Расход' : 'Приход'; ?></td>
                        <td><?php echo $this->escapeHtml($item->getCompany()->getDefaultTitle()); ?></td>
                        <td><?php echo $this->escapeHtml($item->getTitle()); ?></td>
                        <td><?php echo $this->escapeHtml($item->getUser() ? $item->getUser()->getFIO() : ''); ?></td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
            </table>
            <!--            --><?php //echo $this->paginator($paginator, 'office::paginator'); ?>
        </div>
    </div>
</div>
