<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 23.11.18
 * Time: 9:12
 */
/** @var \App\Renderer\PhpRenderer $this */
/** @var \Office\Entity\Processing $item */

/** @var \Office\Entity\Shop[] $shops */

use Office\Entity\Processing;

$this->inlineScript()->prependFile('/assets/cms/vendors/validator/validator.js');
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">

                    <form class="form-horizontal form-label-left" novalidate method="post" action="?">
                        <span class="section">Редактирование чека #<?php echo $item->getId(); ?></span>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="shop">
                                Магазин <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="shop" id="shop" class="form-control col-md-7 col-xs-12" required <?php echo $item->getId() ? 'disabled' : ''; ?>>
                                    <?php
                                    foreach ($shops as $shop) {
                                        ?>
                                        <option
                                                value="<?php echo $shop->getId(); ?>"
                                            <?php echo $item->getShop() && $item->getShop()->getId() === $shop->getId() ? 'selected' : ''; ?>>
                                            <?php echo $this->escapeHtml($shop->getTitle()); ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="operation">
                                Тип <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="operation" id="operation" class="form-control col-md-7 col-xs-12" required>
                                    <?php
                                    foreach (Processing::OPERATION_LIST as $key => $status) {
                                        ?>
                                        <option value="<?php echo $key; ?>" <?php echo $item->getOperation() === $key ? 'selected' : ''; ?>><?php echo $status; ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="status">
                                Статус <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="status" id="status" class="form-control col-md-7 col-xs-12" required>
                                    <?php
                                    foreach (Processing::STATUS_LIST as $key => $status) {
                                        ?>
                                        <option value="<?php echo $key; ?>" <?php echo $item->getStatus() === $key ? 'selected' : ''; ?>><?php echo $status; ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="external_id">
                                Внешний код <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="external_id" class="form-control col-md-7 col-xs-12" name="external_id"
                                       value="<?php echo $item->getExternalId() ?>"
                                       required="required" type="text">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="callback">
                                Callback
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="callback" class="form-control col-md-7 col-xs-12" name="callback"
                                       value="<?php echo $item->getCallbackUrl() ?>"
                                       type="text">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="receipt">
                                Данные чека <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea
                                        class="form-control col-md-7 col-xs-12"
                                        name="receipt"
                                        id="receipt"
                                        cols="30"
                                        rows="10" required><?php echo $item->getRawData(); ?></textarea>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <button id="send" type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <pre>
                            <?php var_dump(json_decode($item->getRawData(), true)) ?>
                        </pre>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
