<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 25.01.18
 * Time: 14:09
 */
/** @var \App\Renderer\PhpRenderer $this */
/** @var \Office\Entity\Kkt[] $kkts */
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Удаленные кассы</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>
                                <a href="<?php echo $this->url(
                                    'admin.kkt.deleted', [], [
                                    'sort' => 'id',
                                    'order' => $order
                                ]
                                ); ?>">
                                    #
                                </a>
                                <?php if ($sortType === 'id') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th>
                                <a href="<?php echo $this->url(
                                    'admin.kkt.deleted', [],
                                    [
                                        'sort' => 'dateDeleted',
                                        'order' => $order
                                    ]
                                ); ?>">
                                    Дата удаления
                                </a>
                                <?php if ($sortType === 'dateDeleted') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th>Магазин</th>
                            <th>Компания</th>
                            <th>Высылать ФН?</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($kkts as $kkt) {
                            ?>
                            <tr>
                                <th scope="row"><?php echo $kkt->getSerialNumber(); ?></th>
                                <td><?php echo $kkt->getDateDeleted() ? $kkt->getDateDeleted()->format('d.m.Y H:i:s') : ''; ?></td>
                                <td>
                                    <?php echo $this->escapeHtml($kkt->getShop()->getTitle()); ?>
                                </td>
                                <td>
                                    <?php echo $this->escapeHtml($kkt->getShop()->getCompany()->getTitle()); ?>
                                </td>
                                <td><?php echo $kkt->getIsSendFn() ? 'Да' : 'Нет'; ?></td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
