<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 22.03.18
 * Time: 19:58
 */
/** @var \App\Renderer\PhpRenderer $this */
/** @var \Office\Entity\Company $company */
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">

                    <h2>Информация о компании <?php echo $this->escapeHtml($company->getDefaultTitle()); ?></h2>
                    <div id="wizard" class="form_wizard wizard_horizontal">
                        <div id="step-1">
                            <form class="form-horizontal form-label-left" method="post" action="?">
                                <span>Сведения о компании</span>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="inn">
                                        ИНН <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="inn" name="inn" required="required" value="<?php echo $this->escapeHtmlAttr($company->getInn()); ?>"
                                               class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyOrgType">
                                        Организационно-правовая форма <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <select id="companyOrgType" name="orgType" required="required" class="form-control col-md-7 col-xs-12">
                                            <option value="0" <?php echo $company->getOrgType() == 0 ? 'selected="selected"' : ''; ?>>Юридическое лицо</option>
                                            <option value="1" <?php echo $company->getOrgType() == 1 ? 'selected="selected"' : ''; ?>>Индивидуальный предприниматель</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group js-company-type-ooo">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyType">
                                        Тип юр.лица <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyType" name="type" required="required" value="<?php echo $this->escapeHtmlAttr($company->getType()); ?>"
                                               class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group js-company-type-ooo">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyTitle">
                                        Наименование юр.лица <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyTitle" name="title" required="required" value="<?php echo $this->escapeHtmlAttr($company->getTitle()); ?>"
                                               class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group js-company-type-ooo">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="kpp">
                                        КПП <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="kpp" name="kpp" required="required" value="<?php echo $this->escapeHtmlAttr($company->getKpp()); ?>"
                                               class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group js-company-type-ooo">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="ogrn">
                                        ОГРН <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="ogrn" name="ogrn" required="required" value="<?php echo $this->escapeHtmlAttr($company->getOgrn()); ?>"
                                               class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group js-company-type-ip" style="display: none">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="ogrnIP">
                                        ОГРНИП <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="ogrnIP" name="ogrnIP" value="<?php echo $this->escapeHtmlAttr($company->getOgrnIp()); ?>" class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyNalogSystem">
                                        Система налогообложения <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <select id="companyNalogSystem" name="nalogSystem" required="required" class="form-control col-md-7 col-xs-12">
                                            <option value="0" <?php echo $company->getNalogSystem() == 0 ? 'selected="selected"' : ''; ?>>ОСН</option>
                                            <option value="1" <?php echo $company->getNalogSystem() == 1 ? 'selected="selected"' : ''; ?>>УСН Доход</option>
                                            <option value="2" <?php echo $company->getNalogSystem() == 2 ? 'selected="selected"' : ''; ?>>УСН Доход минус расход</option>
                                            <option value="3" <?php echo $company->getNalogSystem() == 3 ? 'selected="selected"' : ''; ?>>ЕНВД</option>
                                            <option value="4" <?php echo $company->getNalogSystem() == 4 ? 'selected="selected"' : ''; ?>>ЕСХН</option>
                                            <option value="5" <?php echo $company->getNalogSystem() == 5 ? 'selected="selected"' : ''; ?>>ПСН</option>
                                        </select>
                                    </div>
                                </div>
                                <div style="display: none" class="js-company-type-ip">
                                    <hr>
                                    <span>Индивидуальный предприниматель</span>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyIPLastName">
                                            Фамилия <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="companyIPLastName" name="ipLastName"
                                                   value="<?php echo $this->escapeHtmlAttr($company->getIpLastName()); ?>"
                                                   class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyIPFirstName">
                                            Имя <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="companyIPFirstName" name="ipFirstName"
                                                   value="<?php echo $this->escapeHtmlAttr($company->getIpFirstName()); ?>"
                                                   class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyIPMiddleName">
                                            Отчество <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="companyIPMiddleName" name="ipMiddleName"
                                                   value="<?php echo $this->escapeHtmlAttr($company->getIpMiddleName()); ?>"
                                                   class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                </div>

                                <hr>
                                <span>Контактные данные</span>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyAddress">
                                        Фактический адрес <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyAddress" name="address"
                                               value="<?php echo $this->escapeHtmlAttr($company->getAddress()); ?>"
                                               required="required" class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyPhone">
                                        Телефон <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyPhone" name="companyPhone"
                                               value="<?php echo $this->escapeHtmlAttr($company->getCompanyPhone()); ?>"
                                               required="required" class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyEmail">
                                        E-mail <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyEmail" name="companyEmail"
                                               value="<?php echo $this->escapeHtmlAttr($company->getCompanyEmail()); ?>"
                                               required="required" class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>

                                <hr>
                                <span>Руководитель / представитель</span>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyDirectorLastName">
                                        Фамилия <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyDirectorLastName" name="directorLastName" required="required"
                                               value="<?php echo $this->escapeHtmlAttr($company->getDirectorLastName()); ?>"
                                               class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyDirectorFirstName">
                                        Имя <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyDirectorFirstName" name="directorFirstName" required="required"
                                               value="<?php echo $this->escapeHtmlAttr($company->getDirectorFirstName()); ?>"
                                               class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyDirectorMiddleName">
                                        Отчество <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyDirectorMiddleName" name="directorMiddleName" required="required"
                                               value="<?php echo $this->escapeHtmlAttr($company->getDirectorMiddleName()); ?>"
                                               class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyCheckEmail">
                                        Адрес электронной почты отправителя чека <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="companyCheckEmail" name="companyCheckEmail"
                                               value="<?php echo $this->escapeHtmlAttr($company->getCompanyCheckEmail()); ?>"
                                               required="required" class="form-control col-md-7 col-xs-12">
                                    </div>
                                </div>


                                <div class="actionBar">
                                    <button type="submit" class="btn btn-success">Сохранить</button>
                                </div>
                            </form>

                        </div>
                    </div>
                    <!-- End SmartWizard Content -->
                </div>
            </div>
        </div>
    </div>
</div>
