<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 20.11.18
 * Time: 11:45
 */
/** @var \App\Renderer\PhpRenderer $this */
?>
<footer class="footer">
    <div class="wrapper foot">
        <div class="left-side">
            <div class="col">
                <a href="/upload/docs/confidentiality.pdf" target="_blank">Политика конфиденциальности</a>
                <span>Техническая поддержка: <a href="mailto:online@schetmash.com">online@schetmash.com</a></span>
                <span>Телефон: <a href="tel:+74712734990">+7 (4712) 73-49-90</a></span>
                <span>Режим работы:</span>
                <span>понедельник - пятница с 08.30 до 17.30</span>
                <div class="social-nav">
                    <a href="https://vk.com/schetmash"><i class="fa fa-vk"></i></a>
                </div>
                <a href="https://group.keaz.ru" target="_blank"><img src="/assets/auth/images/GK.png" alt="" class="gk-footer-logo"></a>
            </div>

            <nav class="col">
                <a href="/#howitworks" uk-scroll>Как это работает?</a>
                <a href="/#connect" uk-scroll>Подключение</a>
                <a href="/#calc" uk-scroll>Калькулятор</a>
                <a href="/#advantages" uk-scroll>Преимущества</a>
                <a href="/#faq" uk-scroll>Вопрос-ответ</a>
                <a href="/#integration" uk-scroll>Интеграция</a>
                <a href="/#promo" uk-scroll>Акции</a>
            </nav>

        </div>

        <div class="right-side">
            <div class="col">
                <!--<a href="/">-->АО "Cчётмаш"<br>
                <!--</a>-->
                ИНН 4632126284<br> <span>адрес: 305022, г. Курск,<br>
 ул. 2-я Рабочая, 23, литер В2, помещение 53</span> <a target="_blank" href="/upload/docs/rekvizity.pdf">Реквизиты</a>
            </div>
        </div>


    </div>
</footer>
