<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 25.01.18
 * Time: 14:09
 */
/** @var \App\Renderer\PhpRenderer $this */
/** @var \Office\Entity\Tariff $tariff */

$this->inlineScript()->prependFile('/assets/cms/vendors/validator/validator.js');
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <form class="form-horizontal form-label-left" novalidate method="post" action="?">
                        <span class="section">Редактирование тарифа</span>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">
                                Название <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="title" class="form-control col-md-7 col-xs-12" name="title"
                                       value="<?php echo $tariff->getTitle(); ?>"
                                       required="required" type="text">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">
                                Описание
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea id="description" class="form-control col-md-7 col-xs-12" name="description" rows="5"><?php echo $tariff->getDescription(); ?> </textarea>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="rent_cost">
                                Стоимость аренды <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="rent_cost" class="form-control col-md-7 col-xs-12" name="rent_cost"
                                       value="<?php echo $tariff->getRentCost(); ?>"
                                       required="required" type="number">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="turnover_percent">
                                Процент от оборота
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="turnover_percent" class="form-control col-md-7 col-xs-12" name="turnover_percent"
                                       value="<?php echo $tariff->getTurnoverPercent(); ?>"
                                       type="number">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="month_limit">
                                Ограничение действия тарифа по количеству месяцев
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="month_limit" class="form-control col-md-7 col-xs-12" name="month_limit"
                                       value="<?php echo $tariff->getMonthLimit(); ?>"
                                       type="number">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="month_count">
                                Количество месяцев покупки тарифа как условие подключения <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="month_count" class="form-control col-md-7 col-xs-12" name="month_count"
                                       value="<?php echo $tariff->getMonthCount(); ?>"
                                       required
                                       type="number">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fn_live_time">
                                Срок жизни ФН <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="fn_live_time" id="fn_live_time" class="form-control col-md-7 col-xs-12" required>
                                    <?php
                                    $fnLiveTime = [
                                        15,
                                        36
                                    ];
                                    foreach ($fnLiveTime as $value) {
                                        ?>
                                        <option value="<?php echo $value; ?>" <?php echo $value == $tariff->getFnliveTime() ? 'selected' : ''; ?>>
                                            <?php echo $value; ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="max_turnover">
                                Предельный размер оборота (руб)
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="max_turnover" class="form-control col-md-7 col-xs-12" name="max_turnover"
                                       value="<?php echo $tariff->getMaxTurnover(); ?>"
                                       type="number">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12 control-label">
                                Популярный
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <div class="checkbox">
                                    <label class="">
                                        <div class="icheckbox_flat-green checked" style="position: relative;">
                                            <input type="checkbox" class="flat" name="popular"
                                                <?php echo $tariff->isPopular() ? 'checked="checked"' : '' ?>
                                                   style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper"></ins>
                                        </div>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12 control-label">
                                По умолчанию
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <div class="checkbox">
                                    <label class="">
                                        <div class="icheckbox_flat-green checked" style="position: relative;">
                                            <input type="checkbox" class="flat" name="default"
                                                <?php echo $tariff->isDefault() ? 'checked="checked" readonly="readonly"' : '' ?>
                                                   style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper"></ins>
                                        </div>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="sort">
                                Сортировка <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="sort" class="form-control col-md-7 col-xs-12" name="sort"
                                       value="<?php echo $tariff->getSort(); ?>"
                                       required="required" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12 control-label">
                                Только для новичков
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <div class="checkbox">
                                    <label class="">
                                        <div class="icheckbox_flat-green checked" style="position: relative;">
                                            <input type="checkbox" class="flat" name="beginner"
                                                <?php echo $tariff->getIsBeginner() ? 'checked="checked"' : '' ?>
                                                   style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper"></ins>
                                        </div>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12 control-label">
                                Первый месяц бесплатно
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <div class="checkbox">
                                    <label class="">
                                        <div class="icheckbox_flat-green checked" style="position: relative;">
                                            <input type="checkbox" class="flat" name="promotime"
                                                <?php echo $tariff->getIsPromotime() ? 'checked="checked"' : '' ?>
                                                   style="position: absolute; opacity: 0;">
                                            <ins class="iCheck-helper"></ins>
                                        </div>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <button id="send" type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
