<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 25.01.18
 * Time: 14:09
 */
/** @var \App\Renderer\PhpRenderer $this */
/** @var \App\Entity\Service[] $services */
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Список услуг
                    </h2>
                    <a href="<?php echo $this->url('admin.service.edit', ['id' => 0]); ?>"
                       class="btn btn-primary pull-right">Добавить</a>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>
                                <a href="<?php echo $this->url('admin.service', [], ['sort' => 'id',
                                    'order' => $order]); ?>">
                                    #
                                </a>
                                <?php if ($sortType === 'id') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th>
                                <a href="<?php echo $this->url('admin.service', [],
                                    ['sort' => 'name', 'order' => $order]); ?>">
                                    Название
                                </a>
                                <?php if ($sortType === 'name') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th>
                                <a href="<?php echo $this->url('admin.service', [],
                                    ['sort' => 'measure', 'order' => $order]); ?>">
                                    Ед. измерения
                                </a>
                                <?php if ($sortType === 'measure') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th>
                                <a href="<?php echo $this->url('admin.service', [],
                                    ['sort' => 'price', 'order' => $order]); ?>">
                                    Цена
                                </a>
                                <?php if ($sortType === 'price') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th>
                                <a href="<?php echo $this->url('admin.service', [],
                                    ['sort' => 'defaultValue', 'order' => $order]); ?>">
                                    Кол-во по умолчанию
                                </a>
                                <?php if ($sortType === 'defaultValue') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($services as $service) {
                            ?>
                            <tr>
                                <th scope="row"><?php echo $service->getId(); ?></th>
                                <td>
                                    <a href="<?php echo $this->url('admin.service.edit', ['id' => $service->getId()]); ?>">
                                        <?php echo $service->getName(); ?>
                                    </a>
                                </td>
                                <td>
                                    <?php echo $service->getMeasure(); ?>
                                </td>
                                <td>
                                    <?php echo $service->getPrice(); ?>
                                </td>
                                <td>
                                    <?php echo $service->getDefaultValue(); ?>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
