<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 20.11.18
 * Time: 10:39
 */
/** @var \App\Renderer\PhpRenderer $this */
?>
<section class="banner">
    <div class="banner-head">
        <img src="/upload/content/schetmash.png" alt="">
        <div class="title-block">
            <h1 class="main-title">«Счетмаш Онлайн»</h1>
            <h2 class="main-subtitle">Интернет-касса для Вашего бизнеса <strong>1 месяц бесплатно</strong></h2>
            <a class="plugin-button uk-button uk-button-default uk-margin-small-right" uk-toggle="target: #popup-order" href="#"
               onclick="yaCounter48966332.reachGoal('CONNECT'); return true;">Подключиться</a>
        </div>
    </div>
</section>
<section class="exclamation-block wrapper">
    <div class="exclamation-block-center">
        <div class="exclamation-icon">
            <img src="/upload/content/warning.png" alt="">
        </div>
        <div class="exclamation-text">
            Поскольку теперь при любой онлайн-оплате должен выдаваться чек, владельцам сайтов нужно обеспечить бесперебойную работу кассы. Поэтому, чтобы клиенты смогли совершать
            покупки у Вас 24/7 365 дней в году, Вам необходим сервис «Счетмаш Онлайн».
        </div>
    </div>
</section>
<section class="blue-block-responsive">
    <div class="wrapper">
        <div class="blue-block-text">
            «Счетмаш Онлайн» - это веб-касса для сайтов, где за товары или услуги можно расплатиться онлайн. С помощью этого сервиса покупатели получают электронные чеки, а Ваш
            бизнес в интернете соответствует 54-ФЗ.
        </div>
        <a class="orange-center-button uk-button uk-button-default uk-margin-small-right" uk-toggle="target: #popup-order" href="#">Подключиться</a>
    </div>
</section>
<div class="wrapp center-title">
    <h3>Подключить «Счетмаш Онлайн» просто: <span class="subtitle-mini">мы все сделаем за Вас.</span></h3>
</div>
<div class="wrapper">
    <div class="advantage-block">
        <div class="advantage-item">
            <div class="advantage-item-img">
                <img src="/upload/content/agreement.png" alt="">
            </div>
            <h6 class="advantage-title">Сервис</h6>
            <div class="advantage-item-text">
                Поможем выполнить регистрацию кассового аппарата в налоговой службе, бесплатно предоставим услуги ОФД, интегрируем в Ваш сайт наш сервис.
            </div>
        </div>
        <div class="advantage-item">
            <div class="advantage-item-img">
                <img src="/upload/content/jigsaws.png" alt="">
            </div>
            <h6 class="advantage-title">Кроссплатформенность</h6>
            <div class="advantage-item-text">
                Сервис поддерживает популярные CMS, и мы постоянно расширяем этот список. У «Счетмаш Онлайн» есть открытое API, благодаря которому Вы сможете интегрироваться с
                сервисом в случае, если Ваш сайт имеет не стандартную архитектуру, у Вас CRM или другое решение.
            </div>
        </div>
        <div class="advantage-item">
            <div class="advantage-item-img">
                <img src="/upload/content/data.png" alt="">
            </div>
            <h6 class="advantage-title">Расширяемость</h6>
            <div class="advantage-item-text">
                Вы сможете завести сколько угодно компаний и подключить огромное количество виртуальных веб-касс.
            </div>
        </div>
        <div class="advantage-item">
            <div class="advantage-item-img">
                <img src="/upload/content/gear.png" alt="">
            </div>
            <h6 class="advantage-title">Стабильность</h6>
            <div class="advantage-item-text">
                «Счетмаш Онлайн» дает намного больше стабильности, чем стационарная онлайн-касса, у которой нет гарантий непрерывной работы.
            </div>
        </div>
        <div class="advantage-item">
            <div class="advantage-item-img">
                <img src="/upload/content/distance.png" alt="">
            </div>
            <h6 class="advantage-title">Практичность</h6>
            <div class="advantage-item-text">
                Чтобы использовать этот сервис, Вам не нужно нанимать кассира и организовывать для него рабочее место. Физически веб-кассы находятся у нас, Вы же управляете ими
                дистанционно.
            </div>
        </div>
        <div class="advantage-item">
            <div class="advantage-item-img">
                <img src="/upload/content/smartphone.png" alt="">
            </div>
            <h6 class="advantage-title">Мобильность</h6>
            <div class="advantage-item-text">
                Благодаря «Счетмаш Онлайн» Вы сможете быть в курсе текущих дел даже с мобильного телефона.
            </div>
        </div>
        <a class="orange-center-button on-white uk-button uk-button-default uk-margin-small-right" uk-toggle="target: #popup-order" href="#">Подключиться</a>
    </div>
</div>
<br>
<section class="calc calc-advantage">
    <div class="wrapper">
        <h3>«Счетмаш Онлайн» может выдавать электронные чеки при покупке любых продуктов и услуг, среди которых:</h3>
        <div class="advantage-block">
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/faucet.png" alt="">
                </div>
                <div class="buy-item-title">
                    Жилищно-коммунальные услуги
                </div>
            </div>
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/graduation-hat.png" alt="">
                </div>
                <div class="buy-item-title">
                    Вебинары, курсы
                </div>
            </div>
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/tickets.png" alt="">
                </div>
                <div class="buy-item-title">
                    Авиа- и ж/д билеты
                </div>
            </div>
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/luggage.png" alt="">
                </div>
                <div class="buy-item-title">
                    Бронирование гостиниц
                </div>
            </div>
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/delivery.png" alt="">
                </div>
                <div class="buy-item-title">
                    Доставка еды
                </div>
            </div>
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/text-document-outlined-symbol.png" alt="">
                </div>
                <div class="buy-item-title">
                    Е-ОСАГО
                </div>
            </div>
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/online-shop.png" alt="">
                </div>
                <div class="buy-item-title">
                    Онлайн-сервисы
                </div>
            </div>
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/uniform.png" alt="">
                </div>
                <div class="buy-item-title">
                    Одежда и обувь
                </div>
            </div>
            <div class="buy-item-block">
                <div class="buy-item-icon">
                    <img src="/upload/content/iconsv2/washing-machine.png" alt="">
                </div>
                <div class="buy-item-title">
                    Электронная техника
                </div>
            </div>
        </div>
        <p>И многое другое</p>
    </div>
</section>
<section class="howitworks wrapper" id="howitworks">
    <h2 class="title"> Как это работает? </h2>
    <div class="scheme">
        <img src="/upload/content/howwork/howitworks.jpg" class="full-img" alt=""> <img src="/upload/content/howwork/howitworks960.jpg" class="table-img" alt=""> <img
            src="/upload/content/howwork/howitworks640.jpg" class="phone-large-img" alt=""> <img src="/upload/content/howwork/howitworks380.jpg" class="phone-img" alt="">
    </div>
    <a class="orange-center-button on-white uk-button uk-button-default uk-margin-small-right" uk-toggle="target: #popup-order" href="#">Подключиться</a>
</section>
<!-- - - - - - - - - - - - КАК ПОДКЛЮЧИТЬСЯ - - - - - - - - - - - - - - - - -->
<section class="connect wrapper" id="connect">
    <h2 class="title"> Как подключиться </h2>
    <article class="steps">
        <div class="step wow fadeInUpBig animated" data-wow-duration=".5s">
            <img src="/upload/content/connect2/1.png"> <span class="step-desc">Зарегистрируйтесь в личном кабинете «Счетмаш.Онлайн», указав Ваше Ф.И.О. и контактные данные (e-mail, телефон). Данные для входа в личный кабинет будут отправлены Вам на указанный адрес e-mail. </span>
        </div>
        <div class="step wow fadeInUpBig animated" data-wow-duration="1s">
            <img src="/upload/content/connect2/2.png" alt=""> <span class="step-desc">Внесите информацию о Ваших компаниях. Регистрационные данные компаний заполняются автоматически после выбора организационно-правовой формы (ЮЛ или ИП) и внесения ИНН. Вам остается внести только расчетные реквизиты Ваших компаний. </span>
        </div>
        <div class="step wow fadeInUpBig animated" data-wow-duration="1s">
            <img src="/upload/content/connect2/3.png" alt=""> <span class="step-desc">Добавьте к Вашим компаниям интернет-магазины. Внесите название и адрес интернет-магазина, укажите направление Вашей деятельности. </span>
        </div>
        <div class="step wow fadeInUpBig animated" data-wow-duration="1s">
            <img src="/upload/content/connect2/4.png" alt=""> <span class="step-desc">Выберите необходимое Вам количество касс для каждого, указанного Вами, интернет-магазина. Для удобства пользования нашим сервисом система рекомендует Вам необходимое количество касс, исходя из специфики Вашей деятельности. После ввода данных в Ваш адрес будет направлено письмо со счетом на оказание услуг. </span>
        </div>
        <div class="step wow fadeInUpBig animated" data-wow-duration="1s">
            <img src="/upload/content/connect2/5.png" alt=""> <span class="step-desc">После оплаты счета в Вашем личном кабинете Вы получите данные, необходимые для регистрации кассы. Оформите заявку на регистрацию кассовой техники в личном кабинете ФНС и получите от них регистрационные данные. </span>
        </div>
        <div class="step wow fadeInUpBig animated" data-wow-duration="1s">
            <img src="/upload/content/connect2/6.png" alt=""> <span class="step-desc">Активируйте сервис. Внесите номер РНМ, полученный от ФНС, и нажмите кнопку «Фискализировать ККТ». Касса готова к работе! </span>
        </div>
    </article>
</section>
<section class="banner-rhomb-block">
    <div class="rhombl1-down fadeInUp wow animated" style="visibility: visible; animation-name: fadeInUp;">
    </div>
    <div class="rhombl2-down fadeInUp wow animated" style="visibility: visible; animation-name: fadeInUp;">
    </div>
    <div class="rhombl3-down fadeInUp wow animated" style="visibility: visible; animation-name: fadeInUp;">
    </div>
    <div class="get-cash">
        <div class="promo-red-text">
            Бесплатная регистрация кассы <br>
            при оплате за год! Под ключ.
        </div>
        <a class="plugin-button uk-button uk-button-default uk-margin-small-right" uk-toggle="target: #popup-order" href="#">Получить</a></div>
    <div class="rhombl6-down fadeInRight wow animated" style="visibility: visible; animation-name: fadeInRight;">
    </div>
    <div class="rhombl5-down fadeInRight wow animated" style="visibility: visible; animation-name: fadeInRight;">
    </div>
    <div class="rhombl4-down fadeInRight wow animated" style="visibility: visible; animation-name: fadeInRight;">
    </div>
</section><!-- - - - - - - - - - - - - - КАЛЬКУЛЯТОР - - - - - - - - - - - - - - - - - -->
<section class="calc" id="calc">
    <h2 class="title"> Калькулятор </h2>
    <div class="calculator wrapper">
        <div class="hiddenBlock">
            Задать цену ККМ:
            <div id="cenaKKM">
                1800
            </div>
        </div>
        <div class="hiddenBlock">
            Задать цену ФН:
            <div id="cenaFN">
                6500
            </div>
        </div>
        <form class="right">
            <div class="transaction">
                <label for="transaction">Транзакций в год</label> <input id="intransaction" value="1" type="text"> <input id="transaction" min="1" max="10000000" step="1" value="1"
                                                                                                                          type="range">
            </div>
            <div class="highpoint">
                <label for="highpoint">Пик транзакций в секунду</label> <input id="inhighpoint" value="0" type="text"> <input id="highpoint" min="0" max="100" step="1" value="0"
                                                                                                                              type="range">
            </div>
            <button onclick="yaCounter48966332.reachGoal('CONNECT'); return true;" class="plugin uk-button uk-button-default uk-margin-small-right"
                    uk-toggle="target: #popup-order">Подключиться
            </button>
        </form>
        <div class="left">
            Рекомендованое количество онлайн касс: <span id="fiskal1" class="huge">1</span>
            <div class="periods">
                <div class="period">
                    На 1 месяц: <span class="large"><span id="mount">1800</span> <i class="fa fa-ruble"></i> </span>
                </div>
                <div class="period">
                    На 1 год: <span class="large"><span id="year">21 600</span> <i class="fa fa-ruble"></i> </span>
                </div>
            </div>
            <span>Необходимо <span id="fiskal2" class="medium">1</span> фискальн<span id="suffix0">ых</span> накопите<span id="suffix1">лей</span> + услуги ОФД</span> <span
                class="large"> <span id="summa"> 6 500 </span> <i class="fa fa-ruble"></i> </span>
        </div>
    </div>
</section>
<section class="advantages wrapper" id="advantages">
    <h2 class="title"> Преимущества </h2>
    <div class="adv">
        <div class="advantage wow fadeInLeftBig animated" style="visibility: visible; animation-name: fadeInLeftBig;">
            <div class="image">
                <img src="/upload/content/advan2/img1.png" alt=""> <span class="subtitle">Быстро</span>
            </div>
            <span class="text">Личный кабинет пользователя позволяет осуществить настройку и активировать кассы, внося минимум данных - заполнение регистрационных данных Ваших компаний автоматизировано! Управление услугами, получение различной статистики по кассам, ввод и получение необходимой для регистрации кассы в ФНС информации осуществляется в режиме одного окна.</span>
        </div>
        <div class="advantage wow fadeInUpBig animated" style="visibility: visible; animation-name: fadeInUpBig;">
            <div class="image">
                <img src="/upload/content/advan2/img2.png" alt=""> <span class="subtitle">Надежно</span>
            </div>
            <span class="text">Круглосуточное техническое сопровождение, надежность и энергонезависимость кассовой техники обеспечивает безопасность Ваших данных и доступность сервиса в режиме 24/7/365. Система балансировки нагрузки обеспечивает работоспособность сервиса даже при лавинообразном росте количества продаж Вашего интернет-магазина!</span>
        </div>
        <div class="advantage wow fadeInRightBig animated" style="visibility: visible; animation-name: fadeInRightBig;">
            <div class="image">
                <img src="/upload/content/advan2/img3.jpeg" alt=""> <span class="subtitle">Выгодно</span>
            </div>
            <span class="text">Интеграция нашего сервиса с популярными платежными системами и распространенными CMS-системами сокращает финансовые и временные затраты на приведение Вашего интернет-магазина в соответствие требованиям 54-ФЗ! Интеллектуальная система автоматического мониторинга заранее предупредит Вас о необходимости замены фискального накопителя, что исключит необходимость остановки работы Вашего интернет-магазина.</span>
        </div>
    </div>
    <a class="plugin-button uk-button uk-button-default uk-margin-small-right" uk-toggle="target: #popup-order" href="#">Подключиться</a>
</section><!-- - - - - - - - - - - - - - ВОПРОС-ОТВЕТ - - - - - - - - - - - - - - - - - -->
<section class="faq wrapper" id="faq">
    <h2 class="title"> Вопрос-ответ </h2>

    <ul uk-accordion>
        <li class="uk-open">
            <a class="uk-accordion-title question" href="#">
          <span class="angle">
            <i class="fa fa-chevron-right"></i>
          </span>
                Особенности применения ККТ в интернет-магазине</a>
            <div class="uk-accordion-content answer">
                <p>В соответствии с Федеральным законом 54-ФЗ применение контрольно-кассовой техники при продаже товара в сети интернет с использованием банковских карт обязательно
                    с 01.07.2017 г. Прием к оплате за товар электронных средств платежа делает обязательным применение ККТ с 01.07.2018 г. ККТ применяется вне зависимости от
                    местонахождения покупателя — Федеральный закон 54-ФЗ не делает различий между покупателями, находящимися на территории РФ и находящимися за ее пределами. </p>
            </div>
        </li>
        <li>
            <a class="uk-accordion-title question" href="#">
            <span class="angle">
              <i class="fa fa-chevron-right"></i>
            </span>
                Необходимо ли использовать отдельную ККТ для продаж через интернет магазин?</a>
            <div class="uk-accordion-content answer">
                <p>В кассовом чеке в обязательном порядке указывается адрес точки продаж. Для физического магазина — это адрес местонахождения, а для интернет-магазина — это
                    электронный адрес. Изменение адреса торговой точки производится путем настройки ККТ и фиксируется в ФН. Замена адреса точки продаж может производится на ФН не
                    более 11 раз. На 12-й раз ФН блокируется.
                    При осуществлении расчетов с использованием платежных карт кассовые чеки выдаются покупателям в момент оплаты товара. ст. 5 Закона № 54-ФЗ. Ответственный
                    сотрудник магазина должен в режиме онлайн отслеживать оплаты, что технически невозможно – режим работы интернет магазина 24/7/365.
                    Таким образом применение отдельной ККТ при осуществлении расчетов в сети интернет — обязательно.</p>
            </div>
        </li>
        <li>
            <a class="uk-accordion-title question" href="#">
            <span class="angle">
              <i class="fa fa-chevron-right"></i>
            </span>
                «Оплата на сайте отключена»: типичные ошибки интернет-магазинов после вступления в силу 54-ФЗ</a>
            <div class="uk-accordion-content answer">
                <p>Онлайн-платежи составляют 20–30% от всех платежей интернет-магазинов. Терять клиентов никто не хочет, поэтому нередко магазины предлагают платить через банк. Это
                    не лучший выход. Во-первых, это не так удобно, как по карте. Во-вторых, банки берут комиссию до 7% от суммы покупки. В-третьих, с 01.07.2018 г. чек всё равно
                    нужно выслать покупателю. То же касается оплаты электронными деньгами: «Яндекс.Деньги», Qiwi, EasyPay и других.</p>
            </div>
        </li>

        <li>
            <a class="uk-accordion-title question" href="#">
            <span class="angle">
              <i class="fa fa-chevron-right"></i>
            </span>
                Может ли одна касса использоваться для нескольких интернет-магазинов?</a>
            <div class="uk-accordion-content answer">
                <p>Одну ККТ можно использовать для нескольких интернет-магазинов, если они оформлены на одно юридическое лицо или ИП. При регистрации ККТ в ФНС необходимо указать
                    адреса сайтов интернет-магазинов через запятую.</p>
            </div>
        </li>
    </ul>
</section>
<div class="get-consult">
    <h2 class="subtitle">Получите бесплатную консультацию по&nbsp;54-Ф3 и&nbsp;интернет-кассе</h2>
    <span class="plugin-button uk-button uk-button-default uk-margin-small-right"
          onclick="jivo_api.open(); yaCounter48966332.reachGoal('CONSULTATION'); return true;">Консультация</span>
</div>
<br>
<section class="integration wrapper" id="integration">
    <h2 class="title"> Интеграция </h2>
    <div class="tabs uk-subnav uk-subnav-pill" uk-switcher="">
        <div class="tab uk-active" aria-expanded="true">
            CMS
        </div>
        <div class="tab" aria-expanded="false">
            API
        </div>
        <div class="tab" aria-expanded="false">
            Партнёры
        </div>
    </div>
    <div class="tabs-info uk-switcher uk-margin">
        <div class="tab-info uk-active">
            <div class="tabs-title-size">
                Готовые модули для CMS:
            </div>
            <div class="tabs-title-size-small">
                Нажмите на иконку, чтобы скачать
            </div>
            <div class="cms-logos">
                <a href="https://marketplace.1c-bitrix.ru/solutions/retor.schetmash/" target="_blank" class="cms-logo"><img src="/upload/content/inv/logo1.png" alt=""></a> <span
                    class="cms-info">Бесплатно настроим платежную систему и эквайринг.</span> <a href="https://shop.opencart-russia.ru/schetmash_modul" target="_blank"
                                                                                                 class="cms-logo"><img src="/upload/content/inv/logo2.png" alt=""></a> <a
                    href="/for_cms/webasyst.tar.gz" target="_blank" class="cms-logo"><img src="/upload/content/inv/logo3.png" alt=""></a> <a href="/for_cms/NetCat.zip"
                                                                                                                                             target="_blank"
                                                                                                                                             class="cms-logo"><img
                        src="/upload/content/inv/logo4.png" alt=""></a> <a href="/for_cms/cs.cart.zip" target="_blank" class="cms-logo"><img src="/upload/content/inv/logo5.png"
                                                                                                                                             alt=""></a> <a
                    href="//github.com/hrt4u/django-schetmash-online" target="_blank" class="cms-logo"><img src="/upload/content/inv/logo6.png" alt=""></a> <a
                    href="/for_cms/modschetmash-1.0.0-pl.transport.zip" target="_blank" class="cms-logo"><img src="/upload/content/inv/logo7.png" alt=""></a> <a
                    href="/for_cms/schetmash.zip" target="_blank" class="cms-logo"><img src="/upload/content/inv/logo8.png" alt=""></a>
            </div>
            <div class="tabs-title-size">
                В разработке:
            </div>
            <div class="cms-logos">
                <a class="cms-logo disable" uk-toggle="target: #popup-cms" href="#"> <img src="/upload/content/inv/1.png" alt=""> </a> <a class="cms-logo disable"
                                                                                                                                          uk-toggle="target: #popup-cms" href="#">
                    <img src="/upload/content/inv/2.png" alt=""> </a> <a class="cms-logo disable" uk-toggle="target: #popup-cms" href="#"> <img src="/upload/content/inv/3.png"
                                                                                                                                                alt=""> </a> <a
                    class="cms-logo disable" uk-toggle="target: #popup-cms" href="#"> <img src="/upload/content/inv/4.png" alt=""> </a> <a class="cms-logo disable"
                                                                                                                                           uk-toggle="target: #popup-cms"
                                                                                                                                           href="#"> <img
                        src="/upload/content/inv/5.png" alt=""> </a> <a class="cms-logo disable" uk-toggle="target: #popup-cms" href="#"><img src="/upload/content/inv/6.png"
                                                                                                                                              alt=""></a> <a
                    class="cms-logo disable" uk-toggle="target: #popup-cms" href="#"><img src="/upload/content/inv/7.png" alt=""></a> <a class="cms-logo disable"
                                                                                                                                         uk-toggle="target: #popup-cms"
                                                                                                                                         href="#"><img
                        src="/upload/content/inv/8.png" alt=""></a> <a class="cms-logo disable" uk-toggle="target: #popup-cms" href="#"><img src="/upload/content/inv/9.png"
                                                                                                                                             alt=""></a> <a
                    class="cms-logo disable" uk-toggle="target: #popup-cms" href="#"><img src="/upload/content/inv/10.png" alt=""></a> <a class="cms-logo disable"
                                                                                                                                          uk-toggle="target: #popup-cms"
                                                                                                                                          href="#"><img
                        src="/upload/content/inv/11.png" alt=""></a>
            </div>
            <a class="orange-center-button on-white uk-button uk-button-default uk-margin-small-right" uk-toggle="target: #popup-cms" href="#">У меня другая CMS</a>
            <div id="popup-cms" uk-modal="">
                <div class="popup-cms uk-modal-dialog uk-modal-body">
                    <button class="uk-modal-close-default uk-close uk-icon" type="button" uk-close=""></button>

                    <div id="afbf_err_FID2" class="alx-feedb-error"></div>

                    <div class="afbf alx_feed_back " id="alx_feed_back_FID2">
                        <h2 class="uk-modal-title">Запрос интеграции с CMS</h2>
                        <form id="f_feedback_FID2" name="f_feedback_FID2" action="/" method="post" enctype="multipart/form-data" class="cms-form">
                            <input type="hidden" name="FEEDBACK_FORM_FID2" value="Y"/>

                            <!--<div id="afbf_" class="afbf_item_pole">
<div class="afbf_name">-->
                            <!--<span class="afbf_required_text">*</span>-->                    <!--<div class="afbf_hint"></div>
					</div>-->
                            <!--<div class="afbf_inputtext_bg" id="error_">-->
                            <div style="margin-bottom:10px;">
                                ФИО <span style="color:red;">*</span>
                            </div>
                            <input type="text" size="40" id="FIO_FID21"
                                   name="FIELDS[FIO_FID2]"
                                   class="email-input"
                                   placeholder="Иванов Иван Иванович"/>


                            <div class="afbf_error_text">Это поле обязательно для заполнения</div>
                            <!--</div>-->


                            <!--<div id="afbf_" class="afbf_item_pole">
<div class="afbf_name">-->
                            <!--<span class="afbf_required_text">*</span>-->                    <!--<div class="afbf_hint"></div>
					</div>-->
                            <!--<div class="afbf_inputtext_bg" id="error_">-->
                            <div style="margin-bottom:10px;">
                                Электронный адрес <span style="color:red;">*</span>
                            </div>
                            <input type="text" size="40" id="EMAIL_FID21"
                                   name="FIELDS[EMAIL_FID2]"
                                   class="email-input"
                                   placeholder="email@email.com"/>


                            <div class="afbf_error_text">Введён некорректный e-mail</div>
                            <!--</div>-->


                            <!--<div id="afbf_" class="afbf_item_pole">
<div class="afbf_name">-->
                            <!--<span class="afbf_required_text">*</span>-->                    <!--<div class="afbf_hint"></div>
					</div>-->
                            <!--<div class="afbf_inputtext_bg" id="error_">-->
                            <div style="margin-bottom:10px;">
                                CMS <span style="color:red;">*</span>
                            </div>
                            <input type="text" size="40" id="CMS_FID21"
                                   name="FIELDS[CMS_FID2]"
                                   class="email-input"
                                   placeholder="Opencart"/>


                            <div class="afbf_error_text">Это поле обязательно для заполнения</div>
                            <!--</div>-->

                            <div class="afbf_item_pole">
                                <div class="afbf_name">Текст сообщения</div>
                                <div class="afbf_inputtext_bg" id="error_EMPTY_TEXT">
                                    <textarea class="afbf_textarea" cols="10" rows="10" id="EMPTY_TEXTFID2"
                                              name="FEEDBACK_TEXT_FID2">Прошу реализовать интеграцию с моей CMS</textarea>
                                </div>
                                <div class="afbf_error_text">Это поле обязательно для заполнения</div>
                            </div>
                            <button onclick="yaCounter48966332.reachGoal('CMS'); return true;" type="submit" id="fb_close_FID2" name="SEND_FORM"
                                    value="Отправить" style="text-align:center !important;">Запросить
                            </button>
                            <!--<label data-bx-user-consent="{&quot;id&quot;:1,&quot;sec&quot;:&quot;gyzyh7&quot;,&quot;autoSave&quot;:true,&quot;actionUrl&quot;:&quot;\/local\/components\/bitrix\/main.userconsent.request\/ajax.php&quot;,&quot;replace&quot;:{&quot;button_caption&quot;:&quot;\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c&quot;,&quot;fields&quot;:[&quot;\u0424\u0418\u041e&quot;,&quot;\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441&quot;,&quot;CMS&quot;,&quot;IP-\u0430\u0434\u0440\u0435\u0441&quot;],&quot;INPUT_LABEL&quot;:&quot;\u042f \u0441\u043e\u0433\u043b\u0430\u0441\u0435\u043d \u0441 \u043f\u043e\u043b\u0438\u0442\u0438\u043a\u043e\u0439 \u043a\u043e\u043d\u0444\u0438\u0434\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438 \u0441\u0430\u0439\u0442\u0430.&quot;}}" class="politic-privacy">-->
                            <label for="reg-check" class="register-check">
                                <input type="checkbox" value="Y" checked name="alx_fb_agreement" id="reg-check">
                                <span>Cогласен на <a href="/docs/confidentiality.pdf" target="_blank">обработку персональных данных</a></span>
                            </label>

                            <div class="afbf_error_text">Необходимо ваше согласие на обработку персональных данных</div>
                            <!--                            <script>-->
                            <!--                                BX.message({-->
                            <!--                                    MAIN_USER_CONSENT_REQUEST_TITLE: 'Согласие пользователя',-->
                            <!--                                    MAIN_USER_CONSENT_REQUEST_BTN_ACCEPT: 'Принимаю',-->
                            <!--                                    MAIN_USER_CONSENT_REQUEST_BTN_REJECT: 'Не принимаю',-->
                            <!--                                    MAIN_USER_CONSENT_REQUEST_LOADING: 'Загрузка..',-->
                            <!--                                    MAIN_USER_CONSENT_REQUEST_ERR_TEXT_LOAD: 'Не удалось загрузить текст соглашения.'-->
                            <!---->
                            <!--                                });-->
                            <!--                            </script>-->

                            <input type="hidden" name="sessid" id="sessid_1" value="0010d6b63c098f06ac846c8ef3e16a6b"/></form>
                    </div>

                </div>
            </div>
        </div>
        <div class="tab-info">
            <p>
                Для подключения к сервису Счетмаш онлайн можно использовать API
            </p>
            <div class="buttons">
                <a onclick="yaCounter48966332.reachGoal('DOWNLOADAPI'); return true;" href="/docs/api.pdf" class="button-dark">Скачать документацию по API</a>
            </div>
            <p>
                Данные для тестирования:
            </p>
            <br>
            <p>
                <b>Настройки для модулей CMS следующие:</b>
            </p>
            <p>
                логин: test_api
            </p>
            <p>
                пароль: 123456
            </p>
            <p>
                Id Магазина: 42
            </p>
            <br>
            <p>
                <b> Чтобы зайти в аккаунт тестовой кассы и посмотреть свои чеки:</b>
            </p>
            <p>
                <a href="mailto:testapi@schetmash.com">testapi@schetmash.com</a>
            </p>
            <p>
                Пароль 123456789
            </p>
            <div class="cashbox-count">
                <button type="button" name="button" class="plugin uk-button uk-button-default uk-margin-small-right" uk-toggle="target: #popup-order">Подключиться</button>
            </div>
        </div>
        <div class="tab-info">
            <div class="partner-img">
                <a href="#promo" uk-scroll=""> <img src="/upload/content/inv/robokassa.jpg" alt=""></a>
            </div>
            <p>
                <a href="#promo" uk-scroll="">Получить</a> промокод со скидкой на три месяца от сервиса RoboKassa.
            </p>
            <div class="partner-img">
                <img src="/upload/content/fondy.png" alt="">
            </div>
        </div>
    </div>
</section>
<div id="afbf_err_FID1" class="alx-feedb-error"></div>

<div class="afbf alx_feed_back " id="alx_feed_back_FID1">
    <section class="promocode" id="promo">
        <h2 class="title">Акции</h2>
        <div class="promo wrapper">
            <div class="image-side"><img src="/upload/content/gift3.png" alt=""></div>
            <div class="form-side">
                <h3 class="title">Зарегистрируйтесь в нашем сервисе и получите промокод от платежной системы <img src="/upload/content/logo-robokassa.png" alt="robokassa"></h3>
                <form id="f_feedback_FID1" name="f_feedback_FID1" action="/"
                      action="/" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="FEEDBACK_FORM_FID1" value="Y"/>
                    <input type="hidden" name="HREF_LINK_FID1" value="/"/>
                    <!--<div id="afbf_" class="afbf_item_pole">
<div class="afbf_name">-->
                    <!--<span class="afbf_required_text">*</span>-->                    <!--<div class="afbf_hint"></div>
					</div>-->
                    <!--<div class="afbf_inputtext_bg" id="error_">-->
                    <input type="text" size="40" id="EMAIL_FID11"
                           name="FIELDS[EMAIL_FID1]"
                           value="email@email.com" class="email-input"
                           onclick="if(this.value=='email@email.com'){this.value=''}" placeholder="Введите Ваш email"/>

                    <div class="afbf_error_text">Введён некорректный e-mail</div>
                    <!--</div>-->


                    <button onclick="yaCounter48966332.reachGoal('PROMO'); yaCounter48966332.reachGoal('REGISTRATION'); return true;" type="submit" class="get-gift"
                            id="fb_close_FID1" name="SEND_FORM"
                            value="Отправить">Получить
                    </button>
                    <!--<label data-bx-user-consent="{&quot;id&quot;:1,&quot;sec&quot;:&quot;gyzyh7&quot;,&quot;autoSave&quot;:true,&quot;actionUrl&quot;:&quot;\/local\/components\/bitrix\/main.userconsent.request\/ajax.php&quot;,&quot;replace&quot;:{&quot;button_caption&quot;:&quot;\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c&quot;,&quot;fields&quot;:[&quot;\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441&quot;,&quot;IP-\u0430\u0434\u0440\u0435\u0441&quot;],&quot;INPUT_LABEL&quot;:&quot;\u042f \u0441\u043e\u0433\u043b\u0430\u0441\u0435\u043d \u0441 \u043f\u043e\u043b\u0438\u0442\u0438\u043a\u043e\u0439 \u043a\u043e\u043d\u0444\u0438\u0434\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438 \u0441\u0430\u0439\u0442\u0430.&quot;}}" class="politic-privacy">-->
                    <label class="politic-privacy">
                        <input type="checkbox" value="Y" checked name="alx_fb_agreement">
                        <!--<a>Я согласен с политикой конфиденциальности сайта.</a>-->
                        Согласен с <a href="/docs/confidentiality.pdf" target="_blank">политикой конфиденциальности сайта</a>
                    </label>

                    <div class="afbf_error_text">Необходимо ваше согласие на обработку персональных данных</div>
                    <!--                    <script>-->
                    <!--                        BX.message({-->
                    <!--                            MAIN_USER_CONSENT_REQUEST_TITLE: 'Согласие пользователя',-->
                    <!--                            MAIN_USER_CONSENT_REQUEST_BTN_ACCEPT: 'Принимаю',-->
                    <!--                            MAIN_USER_CONSENT_REQUEST_BTN_REJECT: 'Не принимаю',-->
                    <!--                            MAIN_USER_CONSENT_REQUEST_LOADING: 'Загрузка..',-->
                    <!--                            MAIN_USER_CONSENT_REQUEST_ERR_TEXT_LOAD: 'Не удалось загрузить текст соглашения.'-->
                    <!---->
                    <!--                        });-->
                    <!--                    </script>-->


                    <input type="hidden" name="sessid" id="sessid_2" value="0010d6b63c098f06ac846c8ef3e16a6b"/></form>
            </div>
        </div>
    </section>
</div>
<section class="clients">
    <h2 class="title">Клиенты</h2>
    <div class="wrapper">
        <div class="owl-carousel owl-theme slider">
            <div class="slider-item"><img src="/upload/content/clients/1.jpg" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/2.jpg" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/3.png" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/4.jpg" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/5.png" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/6.png" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/7.jpg" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/8.jpg" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/9.jpg" alt=""></div>
            <div class="slider-item"><img src="/upload/content/clients/10.png" alt=""></div>
        </div>
    </div>
</section>
<style type="text/css">
    #alx_feed_back_FID1.alx_feed_back,
    #afbf_err_FID1.alx-feedb-error {
        width: 50%;
    }
</style>
<style type="text/css">
    #alx_feed_back_FID2.alx_feed_back,
    #afbf_err_FID2.alx-feedb-error {
        width: 50%;
    }
</style>

