<?php
/** @var \App\Renderer\PhpRenderer $this */
/** @var \App\Entity\File $file */
/** @var \App\Entity\FileCategory[] $categories */
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">

                    <form class="form-horizontal form-label-left js-kkt-edit-from" novalidate method="post" action="?">
                        <span class="section">
                            Редактирование файла <?php echo $file->getFilename(); ?>
                        </span>

                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">
                                Название
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="title" class="form-control col-md-7 col-xs-12" name="title"
                                       value="<?php echo $file->getTitle(); ?>"
                                       type="text">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="file">
                                Файл <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="rnm" class="form-control col-md-7 col-xs-12" name="file" type="file">
                            </div>
                        </div>
                        <?php
                        if ($file->getFilename()) {
                            ?>
                            <div class="item form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <span class="label label-success">
                                        Загружен
                                    </span>
                                    <a href="<?php echo $file->getFilename(); ?>"> скачать</a>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="order">
                                Сортировка
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="title" class="form-control col-md-7 col-xs-12" name="order"
                                       value="<?php echo $file->getOrder(); ?>"
                                       type="number">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="categoryId">
                                Категория
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select
                                        name="categoryId"
                                        id="categoryId"
                                        class="form-control col-md-7 col-xs-12"
                                >
                                    <?php
                                    foreach ($categories as $category) {
                                        ?>
                                        <option value="<?php echo $category->getId(); ?>"
                                            <?php echo $file->getCategory() === $category ? 'selected' : ''; ?>
                                        >
                                            <?php echo $category->getTitle(); ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
